liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
liquibase.datasource.url=jdbc:mysql://localhost:3306/mydb
liquibase.datasource.username=myuser
liquibase.datasource.password=
liquibase.datasource.driver=com.mysql.cj.jdbc.Driver