liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
liquibase.datasource.url=jdbc:postgresql://localhost:5432/mydb
liquibase.datasource.username=myuser
liquibase.datasource.password=
liquibase.datasource.driver=org.postgresql.Driver